### PR TITLE
Add Python build and tests

### PR DESCRIPTION
**Pull request by lrettig**
- [x] add python build
- [x] add python build makefile recipe
- [x] add python build makefile recipe to make build
- [x] add python test
- [x] add python test makefile recipe
- [ ] add documentation

### CODE REVIEW

**Comment by avive** [comment]
why do we need a python build system? curious...

**Comment by lrettig** [comment]
System tests are all written in Python and need to be migrated. See https://github.com/spacemeshos/go-spacemesh/issues/2185

**Comment by poszu** [comment]
@lrettig, it seems that the python tests are gone. Can this PR be closed?

**Comment by lrettig** [comment]
It's not especially critical but it would still be nice to include a python build here - I think it's likely we'll use python in the future for tooling, testing, simulation, etc. Ideally we'd add typescript and maybe one or two other languages too.

**Comment by poszu** [comment]
> It's not especially critical but it would still be nice to include a python build here - I think it's likely we'll use python in the future for tooling, testing, simulation, etc. Ideally we'd add typescript and maybe one or two other languages too.

Then I'd suggest closing it and reopening it when there is a use case for it.

**Comment by lrettig** [comment]
Okay

**Pull request closed without merging**
