### PR TITLE
Add state delta to tx receipts

### LINKED ISSUE #34: Add state delta and transaction index to TransactionReceipt
Per Tal on today's design review call.

Transaction index is either the index of a tx within a layer (in order of execution, based on output of consensus), or else a global "serial number" of a tx (same thing but across all layers since genesis).

State delta will require some thought. For simple coin tx, it's a list of {accountId: balance change}, as well as the counter (nonce) change for the sender's account. For a smart contract tx, it can additionally include updates to state for one or more smart contracts. For a "create contract" tx, it will also include an update to the newly-created contract address's code.

### PR DESCRIPTION
**Pull request by lrettig**
Tx index was added already in https://github.com/spacemeshos/api/commit/1b4ca35d24c0eb1aa1ae7980570080442e1bd9f0

This adds the second requirement, state delta

Closes #34

### CODE REVIEW

**Comment by avive** [comment]
You should get @YaronWittenstein involved in this and in any API issues such as this which is SVM related - he's been working on svm data in receipts over the last few days...

1. What you propose is a list of decoded key-values. The approach I talked with Yaron and I think what he's building is having packed binary svm data in the receipts where it is the responsibility of clients to decode it (e.g. smapp and explore front-end) using the svm-codec lib. What you proposing will require the node to decode lots of svm data per receipt to create it at request time or at the time it is generated by the node. 

2. We need to talk about the idea to log every variable change in svm. I think that the current thinking was to just include the updated storage root hash in the receipt and so clients can run the computation and compare storage hashes to validate vars change. It is not a bad idea to include (k,v) of every changed value in the receipt.

**Comment by YaronWittenstein** [comment]
I think that `GlobalState` will do that without involving SVM.

This SMIP describes the interface between SVM and the `Global State`:
https://github.com/spacemeshos/SMIPS/issues/20

**Comment by lrettig** [comment]
> just include the updated storage root hash in the receipt and so clients can run the computation and compare storage hashes to validate vars change.

It's not reasonable to expect clients to "run the computation" - they don't have an SVM interpreter nor do they have all the context.

**Comment by lrettig** [comment]
> The `STF` component should be able to ask the `GloblState` for all the `(k, v)` changes and flush to disk at one call all the changes at once.

Great - then it shouldn't be too hard to include this in the tx receipt

**Comment by YaronWittenstein** [comment]
> > just include the updated storage root hash in the receipt and so clients can run the computation and compare storage hashes to validate vars change.
> 
> It's not reasonable to expect clients to "run the computation" - they don't have an SVM interpreter nor do they have all the context.

@lrettig @avive I think I'm not following - I thought that the each Full-Node executes each transaction.
So the Receipt's outcode `App State` is only for validation.

**Comment by YaronWittenstein** [comment]
> > The `STF` component should be able to ask the `GloblState` for all the `(k, v)` changes and flush to disk at one call all the changes at once.
> 
> Great - then it shouldn't be too hard to include this in the tx receipt

As I've written in the previous message here - Why do we need to save all the `(k, v)` changes as part of the Receipt?

**Comment by lrettig** [comment]
> > > just include the updated storage root hash in the receipt and so clients can run the computation and compare storage hashes to validate vars change.
> > 
> > It's not reasonable to expect clients to "run the computation" - they don't have an SVM interpreter nor do they have all the context.
> 
> @lrettig @avive I think I'm not following - I thought that the each Full-Node executes each transaction.
> So the Receipt's outcode `App State` is only for validation.

By client I don't mean full node. I mean something like a web app.

Why include all state changes? Because even a full node can't calculate these for itself without storing all intermediate, historical state.

**Comment by YaronWittenstein** [comment]
But the changes are sitting already in the `Global State` - why replicate that data to the Receipts?

**Comment by lrettig** [comment]
Yes, the global state is updated as a side effect of executing a transaction, but the list of state changes from each tx is not stored by a full node (only maybe an archive node)

**Comment by fasmat** [comment]
Closed due to inactivity

**Pull request closed without merging**
